leds:
  rectangle_origin: [372, 755]
  rectangle_size: [115, 80]

  K1:
    origin: [95, 12]
    radius: 2
    color: [66, 88, 142]
  K2:
    origin: [96, 25]
    radius: 3
    color: [66, 88, 142]
  K3:
    origin: [96, 40]
    radius: 3
    color: [66, 88, 142]
  S1:
    origin: [21, 15]
    radius: 5      
    color: [153, 191, 176]
  S2:
    origin: [21, 30]
    radius: 5      
    color: [153, 191, 176]
  S3:
    origin: [21, 44]
    radius: 5      
    color: [153, 191, 176]
  S4:
    origin: [21, 58]
    radius: 5
    color: [153, 191, 176]
  Status: 
    origin: [51, 62]
    radius: 5
    color: [153, 191, 176]
  Error: 
    origin: [75, 60]
    radius: 3
    color: [66, 88, 142]  
  Black:
    origin: [93, 60]
    radius: 8
    color: [0 , 0 , 0]


lcd:
  rectangle_origin: [1837, 1152]
  rectangle_size: [114, 58]