leds:
  rectangle_origin: [372, 755]
  rectangle_size: [115, 80]

  K1:
    origin: [95, 12]
    radius: 3
  K2:
    origin: [96, 25]
    radius: 3
  K3:
    origin: [96, 40]
    radius: 3
  S1:
    origin: [21, 15]
    radius: 5      
  S2:
    origin: [21, 30]
    radius: 5      
  S3:
    origin: [21, 44]
    radius: 5      
  S4:
    origin: [21, 58]
    radius: 5
  Status: 
    origin: [51, 62]
    radius: 5
  Error: 
    origin: [75, 60]
    radius: 3
  Black:
    origin: [93, 60]
    radius: 8


lcd:
  rectangle_origin: [1827, 1142]
  rectangle_size: [140, 85]
  screen: [[10,15], [120,18], [120,60], [17,60]]